% Author: Gerardo Parra, Modified by GG on 02.10.2023

%% inputs
% computer setting
computer    = 'pc';  % 'mac' or 'pc'
rcfs_path = fullfile('Groups','LCN-Nelson-LEAP','Groups','BCH');

% data location
data_path     = fullfile(rcfs_path,'EEG','eeg_processed_data');
% subdir        = 'filtered_processed_for_FC_2-16-2023';
% subdir        = 'mff_for_processing';
subdir        = '';

% toggle 'modules'
run_happe  = 1;
run_genERP = 0;
rerun      = 0;
previously_ran_MuscIL = 0;

% happer inputs
% param_dir = fullfile( rcfs_path,'Data processing','Scripts', ...
%                       'happe+er','input_params','harmonized_2022-12',...
%                       'from_LG_updated_filters');

param_dir = fullfile( rcfs_path,'Data processing','Scripts', ...
                      'happe+er','input_params','harmonized_2022-12');
params_genERP = 'genERP_parameters_06-07-2022.mat';
params_happe  = {
%                     'inputParameters_baseline_UPDATED_FILTERS_2023-03-07.mat'
                    'inputParameters_baseline_2023-03-06.mat',...
%                     'inputParameters_VEP_UPDATED_FILTERS_FOR_FC.mat'
%                     'inputParameters_baseline_UPDATED_FILTERS_FOR_FC.mat'
%                     'inputParameters_VEP_2022-12-20.mat'
%                     'inputParameters_baseline_5sec.mat',          ...
%                     'inputParameters_baseline_2022-12-15.mat',          ...
%                     'inputParameters_auditory_2022-10-10.mat',          ...
%                     'inputParameters_VEP_2022-10-08.mat',               ...
%                     'inputParameters_disengagement_2022-10-11.mat',     ...
%                       'inputParameters_flanker_test_2022-10-11.mat',      ...
%                     'inputParameters_WM_ISI_2022-10-11.mat',            ...
%                     'inputParameters_WM_stim_duration_2022-10-11.mat'   ...
                };
run_tag   = {
                '_BASELINE',...
%                 '_BASELINE_5sec',        ...
%                 '_AUDITORY',        ...
%                 '_VEP',             ...
%                 '_DISENGAGEMENT',   ...
%                  '_FLANKER',         ...
%                 '_WM_ISI',          ...
%                 '_WM_stim_duration' ...
            };

% age groups to search for files
age_groups = {
%                 'serotonin_test_processing'
%                 'dopamine_test_processing',...
%                 '03_months',...
%                 '04_months',...
%                 '05_months',...
%                 '06_months',...
%                 '08_months',...
%                 '10_months',...
%                 '12_months',...
%                 '14_months',...
%                 '16_months',...
                '18_months',...
%                 '24_months',...
%                 '30_months',...
%                 '36_months' ...
%                 'updated_segmentation_test'
              };
n_ages = length(age_groups);

%% run happe+er scripts
% set up paths based on computer setting
switch computer
    case 'mac'
        path_prefix = '\\rc-fs.tch.harvard.edu\dmc-nelson'; 
    case 'pc'
        path_prefix = 'Z:';
end
param_dir = fullfile(path_prefix,param_dir);
data_path = fullfile(path_prefix,data_path);

% iterate through age groups and run HAPPE+ER
if run_happe
    for i_p = 1:length(params_happe)
        param_path = fullfile(param_dir,params_happe{i_p});
        for i_a = 1:n_ages
            age = age_groups{i_a};
            age_path = fullfile(data_path,subdir,age);
            HAPPE_v3_BCH_20230331(age_path,rerun,run_tag{i_p},param_path);
        end
    end
end

% iterate through ages and run genERPs
% if run_genERP
%     for i_p = 1:length(params_happe)
%         param_path = fullfile(param_dir,params_genERP);
%         for i_a = 1:n_ages
%             age = age_groups{i_a};
%             age_path = fullfile(data_path,age,subdir,'5 - processed');
%             generateERPs_auto(age_path,param_path,run_tag{i_p});
%         end
%     end
% end